version: "2.3"

services:
  postgres-moleculus_final:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin3
      - POSTGRES_USER=admin3
      - POSTGRES_DB=moleculus_db_final
    volumes:
      - postgres-data:/var/lib/postgresql/nest_data

volumes:
  postgres-data:
    driver: local
